/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JavaRefresher;

public class App {
   
    public static void main(String[] args) {
        System.out.println("HELLO");
    }
}
