/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vscodejava;
import java.util.Scanner;

public class App {


    public static void main(String[] args) {    


        int variableinteger = 1;

        System.out.println(variableinteger+2);


    }
}
