/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vscodejava;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {    


        Scanner scanner = new Scanner(System.in);

        // Prompt the user to enter their name
        System.out.print("Enter your name: ");

        // Read the user's input as a string
        String name = scanner.nextLine();

        System.out.println("name is "+name);
        

    }
}
